//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: vesting
// ----------------------------------------------------------------------------
pub mod vesting {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for vesting
    pub fn program_id() -> Pubkey {
        pubkey!("G6iaigUdi2btFwUc2N65twfxwA8Ew5uKKhKJ5RJa8wvu")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CancelCampaign
    // ....................................................................

    /// Main instruction struct for CancelCampaign
    pub struct CancelCampaignInstruction {
        pub accounts: CancelCampaignInstructionAccountMetas,
        pub data: CancelCampaignInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelCampaign instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelCampaignInstructionAccountMetas {
        pub cancel_authority: AccountMeta,

        pub vesting_tree: AccountMeta,
    }

    /// Account pubkeys for CancelCampaign instruction
    #[derive(Debug, Clone)]
    pub struct CancelCampaignInstructionAccounts {
        pub cancel_authority: Pubkey,

        pub vesting_tree: Pubkey,
    }

    impl CancelCampaignInstructionAccounts {
        pub fn new(cancel_authority: Pubkey, vesting_tree: Pubkey) -> Self {
            Self {
                cancel_authority,

                vesting_tree,
            }
        }
    }

    /// Instruction data for CancelCampaign
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelCampaignInstructionData {}

    impl CancelCampaignInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelCampaignInstruction
    impl CancelCampaignInstruction {
        fn discriminator() -> [u8; 8] {
            [66u8, 10u8, 32u8, 138u8, 122u8, 36u8, 134u8, 202u8]
        }

        pub fn data(data: CancelCampaignInstructionData) -> Self {
            Self {
                accounts: CancelCampaignInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelCampaignInstructionAccounts) -> Self {
            self.accounts.cancel_authority =
                AccountMeta::new_readonly(accounts.cancel_authority, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.cancel_authority.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Claim
    // ....................................................................

    /// Main instruction struct for Claim
    pub struct ClaimInstruction {
        pub accounts: ClaimInstructionAccountMetas,
        pub data: ClaimInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Claim instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimInstructionAccountMetas {
        pub beneficiary: AccountMeta,

        pub vesting_tree: AccountMeta,

        pub claim_record: AccountMeta,

        pub vault_authority: AccountMeta,

        pub vault: AccountMeta,

        pub beneficiary_ata: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Claim instruction
    #[derive(Debug, Clone)]
    pub struct ClaimInstructionAccounts {
        pub beneficiary: Pubkey,

        pub vesting_tree: Pubkey,

        pub claim_record: Pubkey,

        pub vault_authority: Pubkey,

        pub vault: Pubkey,

        pub beneficiary_ata: Pubkey,

        pub mint: Pubkey,
    }

    impl ClaimInstructionAccounts {
        pub fn new(
            beneficiary: Pubkey,

            vesting_tree: Pubkey,

            claim_record: Pubkey,

            vault_authority: Pubkey,

            vault: Pubkey,

            beneficiary_ata: Pubkey,

            mint: Pubkey,
        ) -> Self {
            Self {
                beneficiary,

                vesting_tree,

                claim_record,

                vault_authority,

                vault,

                beneficiary_ata,

                mint,
            }
        }
    }

    /// Instruction data for Claim
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimInstructionData {
        pub leaf: VestingLeaf,

        pub proof: Vec<[u8; 32]>,
    }

    impl ClaimInstructionData {
        pub fn new(leaf: VestingLeaf, proof: Vec<[u8; 32]>) -> Self {
            Self { leaf, proof }
        }
    }

    /// Implementation for ClaimInstruction
    impl ClaimInstruction {
        fn discriminator() -> [u8; 8] {
            [62u8, 198u8, 214u8, 193u8, 213u8, 159u8, 108u8, 210u8]
        }

        pub fn data(data: ClaimInstructionData) -> Self {
            Self {
                accounts: ClaimInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimInstructionAccounts) -> Self {
            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self.accounts.claim_record = AccountMeta::new(accounts.claim_record, false);

            self.accounts.vault_authority =
                AccountMeta::new_readonly(accounts.vault_authority, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.beneficiary_ata = AccountMeta::new(accounts.beneficiary_ata, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.push(self.accounts.claim_record.clone());

            metas.push(self.accounts.vault_authority.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.beneficiary_ata.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CloseClaimRecord
    // ....................................................................

    /// Main instruction struct for CloseClaimRecord
    pub struct CloseClaimRecordInstruction {
        pub accounts: CloseClaimRecordInstructionAccountMetas,
        pub data: CloseClaimRecordInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CloseClaimRecord instruction
    #[derive(Debug, Clone, Default)]
    pub struct CloseClaimRecordInstructionAccountMetas {
        pub beneficiary: AccountMeta,

        pub vesting_tree: AccountMeta,

        pub claim_record: AccountMeta,
    }

    /// Account pubkeys for CloseClaimRecord instruction
    #[derive(Debug, Clone)]
    pub struct CloseClaimRecordInstructionAccounts {
        pub beneficiary: Pubkey,

        pub vesting_tree: Pubkey,

        pub claim_record: Pubkey,
    }

    impl CloseClaimRecordInstructionAccounts {
        pub fn new(beneficiary: Pubkey, vesting_tree: Pubkey, claim_record: Pubkey) -> Self {
            Self {
                beneficiary,

                vesting_tree,

                claim_record,
            }
        }
    }

    /// Instruction data for CloseClaimRecord
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CloseClaimRecordInstructionData {}

    impl CloseClaimRecordInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CloseClaimRecordInstruction
    impl CloseClaimRecordInstruction {
        fn discriminator() -> [u8; 8] {
            [250u8, 193u8, 24u8, 86u8, 13u8, 34u8, 66u8, 240u8]
        }

        pub fn data(data: CloseClaimRecordInstructionData) -> Self {
            Self {
                accounts: CloseClaimRecordInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CloseClaimRecordInstructionAccounts) -> Self {
            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, true);

            self.accounts.vesting_tree = AccountMeta::new_readonly(accounts.vesting_tree, false);

            self.accounts.claim_record = AccountMeta::new(accounts.claim_record, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.push(self.accounts.claim_record.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateCampaign
    // ....................................................................

    /// Main instruction struct for CreateCampaign
    pub struct CreateCampaignInstruction {
        pub accounts: CreateCampaignInstructionAccountMetas,
        pub data: CreateCampaignInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateCampaign instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateCampaignInstructionAccountMetas {
        pub creator: AccountMeta,

        pub vesting_tree: AccountMeta,

        pub vault_authority: AccountMeta,

        pub vault: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for CreateCampaign instruction
    #[derive(Debug, Clone)]
    pub struct CreateCampaignInstructionAccounts {
        pub creator: Pubkey,

        pub vesting_tree: Pubkey,

        pub vault_authority: Pubkey,

        pub vault: Pubkey,

        pub mint: Pubkey,
    }

    impl CreateCampaignInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            vesting_tree: Pubkey,

            vault_authority: Pubkey,

            vault: Pubkey,

            mint: Pubkey,
        ) -> Self {
            Self {
                creator,

                vesting_tree,

                vault_authority,

                vault,

                mint,
            }
        }
    }

    /// Instruction data for CreateCampaign
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateCampaignInstructionData {
        pub args: CreateCampaignArgs,
    }

    impl CreateCampaignInstructionData {
        pub fn new(args: CreateCampaignArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for CreateCampaignInstruction
    impl CreateCampaignInstruction {
        fn discriminator() -> [u8; 8] {
            [111u8, 131u8, 187u8, 98u8, 160u8, 193u8, 114u8, 244u8]
        }

        pub fn data(data: CreateCampaignInstructionData) -> Self {
            Self {
                accounts: CreateCampaignInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateCampaignInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self.accounts.vault_authority =
                AccountMeta::new_readonly(accounts.vault_authority, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.push(self.accounts.vault_authority.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateStream
    // ....................................................................

    /// Main instruction struct for CreateStream
    pub struct CreateStreamInstruction {
        pub accounts: CreateStreamInstructionAccountMetas,
        pub data: CreateStreamInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateStream instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateStreamInstructionAccountMetas {
        pub creator: AccountMeta,

        pub vesting_tree: AccountMeta,

        pub vault_authority: AccountMeta,

        pub vault: AccountMeta,

        pub source_ata: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for CreateStream instruction
    #[derive(Debug, Clone)]
    pub struct CreateStreamInstructionAccounts {
        pub creator: Pubkey,

        pub vesting_tree: Pubkey,

        pub vault_authority: Pubkey,

        pub vault: Pubkey,

        pub source_ata: Pubkey,

        pub mint: Pubkey,
    }

    impl CreateStreamInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            vesting_tree: Pubkey,

            vault_authority: Pubkey,

            vault: Pubkey,

            source_ata: Pubkey,

            mint: Pubkey,
        ) -> Self {
            Self {
                creator,

                vesting_tree,

                vault_authority,

                vault,

                source_ata,

                mint,
            }
        }
    }

    /// Instruction data for CreateStream
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateStreamInstructionData {
        pub args: CreateStreamArgs,
    }

    impl CreateStreamInstructionData {
        pub fn new(args: CreateStreamArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for CreateStreamInstruction
    impl CreateStreamInstruction {
        fn discriminator() -> [u8; 8] {
            [71u8, 188u8, 111u8, 127u8, 108u8, 40u8, 229u8, 158u8]
        }

        pub fn data(data: CreateStreamInstructionData) -> Self {
            Self {
                accounts: CreateStreamInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateStreamInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self.accounts.vault_authority =
                AccountMeta::new_readonly(accounts.vault_authority, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.source_ata = AccountMeta::new(accounts.source_ata, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.push(self.accounts.vault_authority.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.source_ata.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FundCampaign
    // ....................................................................

    /// Main instruction struct for FundCampaign
    pub struct FundCampaignInstruction {
        pub accounts: FundCampaignInstructionAccountMetas,
        pub data: FundCampaignInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FundCampaign instruction
    #[derive(Debug, Clone, Default)]
    pub struct FundCampaignInstructionAccountMetas {
        pub creator: AccountMeta,

        pub vesting_tree: AccountMeta,

        pub vault: AccountMeta,

        pub source_ata: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FundCampaign instruction
    #[derive(Debug, Clone)]
    pub struct FundCampaignInstructionAccounts {
        pub creator: Pubkey,

        pub vesting_tree: Pubkey,

        pub vault: Pubkey,

        pub source_ata: Pubkey,
    }

    impl FundCampaignInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            vesting_tree: Pubkey,

            vault: Pubkey,

            source_ata: Pubkey,
        ) -> Self {
            Self {
                creator,

                vesting_tree,

                vault,

                source_ata,
            }
        }
    }

    /// Instruction data for FundCampaign
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FundCampaignInstructionData {
        pub amount: u64,
    }

    impl FundCampaignInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for FundCampaignInstruction
    impl FundCampaignInstruction {
        fn discriminator() -> [u8; 8] {
            [109u8, 57u8, 56u8, 239u8, 99u8, 111u8, 221u8, 121u8]
        }

        pub fn data(data: FundCampaignInstructionData) -> Self {
            Self {
                accounts: FundCampaignInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FundCampaignInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.source_ata = AccountMeta::new(accounts.source_ata, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.source_ata.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: GetVestedAmount
    // ....................................................................

    /// Main instruction struct for GetVestedAmount
    pub struct GetVestedAmountInstruction {
        pub accounts: GetVestedAmountInstructionAccountMetas,
        pub data: GetVestedAmountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for GetVestedAmount instruction
    #[derive(Debug, Clone, Default)]
    pub struct GetVestedAmountInstructionAccountMetas {}

    /// Account pubkeys for GetVestedAmount instruction
    #[derive(Debug, Clone)]
    pub struct GetVestedAmountInstructionAccounts {}

    impl GetVestedAmountInstructionAccounts {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Instruction data for GetVestedAmount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct GetVestedAmountInstructionData {
        pub leaf: VestingLeaf,

        pub cancelled_at: Option<i64>,

        pub now: i64,
    }

    impl GetVestedAmountInstructionData {
        pub fn new(leaf: VestingLeaf, cancelled_at: Option<i64>, now: i64) -> Self {
            Self {
                leaf,

                cancelled_at,

                now,
            }
        }
    }

    /// Implementation for GetVestedAmountInstruction
    impl GetVestedAmountInstruction {
        fn discriminator() -> [u8; 8] {
            [89u8, 97u8, 185u8, 152u8, 211u8, 78u8, 203u8, 193u8]
        }

        pub fn data(data: GetVestedAmountInstructionData) -> Self {
            Self {
                accounts: GetVestedAmountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: GetVestedAmountInstructionAccounts) -> Self {
            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: PauseCampaign
    // ....................................................................

    /// Main instruction struct for PauseCampaign
    pub struct PauseCampaignInstruction {
        pub accounts: PauseCampaignInstructionAccountMetas,
        pub data: PauseCampaignInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for PauseCampaign instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseCampaignInstructionAccountMetas {
        pub pause_authority: AccountMeta,

        pub vesting_tree: AccountMeta,
    }

    /// Account pubkeys for PauseCampaign instruction
    #[derive(Debug, Clone)]
    pub struct PauseCampaignInstructionAccounts {
        pub pause_authority: Pubkey,

        pub vesting_tree: Pubkey,
    }

    impl PauseCampaignInstructionAccounts {
        pub fn new(pause_authority: Pubkey, vesting_tree: Pubkey) -> Self {
            Self {
                pause_authority,

                vesting_tree,
            }
        }
    }

    /// Instruction data for PauseCampaign
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseCampaignInstructionData {}

    impl PauseCampaignInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseCampaignInstruction
    impl PauseCampaignInstruction {
        fn discriminator() -> [u8; 8] {
            [62u8, 247u8, 54u8, 192u8, 240u8, 158u8, 8u8, 161u8]
        }

        pub fn data(data: PauseCampaignInstructionData) -> Self {
            Self {
                accounts: PauseCampaignInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseCampaignInstructionAccounts) -> Self {
            self.accounts.pause_authority =
                AccountMeta::new_readonly(accounts.pause_authority, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pause_authority.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UnpauseCampaign
    // ....................................................................

    /// Main instruction struct for UnpauseCampaign
    pub struct UnpauseCampaignInstruction {
        pub accounts: UnpauseCampaignInstructionAccountMetas,
        pub data: UnpauseCampaignInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UnpauseCampaign instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseCampaignInstructionAccountMetas {
        pub pause_authority: AccountMeta,

        pub vesting_tree: AccountMeta,
    }

    /// Account pubkeys for UnpauseCampaign instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseCampaignInstructionAccounts {
        pub pause_authority: Pubkey,

        pub vesting_tree: Pubkey,
    }

    impl UnpauseCampaignInstructionAccounts {
        pub fn new(pause_authority: Pubkey, vesting_tree: Pubkey) -> Self {
            Self {
                pause_authority,

                vesting_tree,
            }
        }
    }

    /// Instruction data for UnpauseCampaign
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseCampaignInstructionData {}

    impl UnpauseCampaignInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseCampaignInstruction
    impl UnpauseCampaignInstruction {
        fn discriminator() -> [u8; 8] {
            [177u8, 111u8, 91u8, 206u8, 169u8, 242u8, 87u8, 95u8]
        }

        pub fn data(data: UnpauseCampaignInstructionData) -> Self {
            Self {
                accounts: UnpauseCampaignInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseCampaignInstructionAccounts) -> Self {
            self.accounts.pause_authority =
                AccountMeta::new_readonly(accounts.pause_authority, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pause_authority.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateRoot
    // ....................................................................

    /// Main instruction struct for UpdateRoot
    pub struct UpdateRootInstruction {
        pub accounts: UpdateRootInstructionAccountMetas,
        pub data: UpdateRootInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateRoot instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateRootInstructionAccountMetas {
        pub cancel_authority: AccountMeta,

        pub vesting_tree: AccountMeta,
    }

    /// Account pubkeys for UpdateRoot instruction
    #[derive(Debug, Clone)]
    pub struct UpdateRootInstructionAccounts {
        pub cancel_authority: Pubkey,

        pub vesting_tree: Pubkey,
    }

    impl UpdateRootInstructionAccounts {
        pub fn new(cancel_authority: Pubkey, vesting_tree: Pubkey) -> Self {
            Self {
                cancel_authority,

                vesting_tree,
            }
        }
    }

    /// Instruction data for UpdateRoot
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateRootInstructionData {
        pub new_root: [u8; 32],

        pub new_leaf_count: u32,
    }

    impl UpdateRootInstructionData {
        pub fn new(new_root: [u8; 32], new_leaf_count: u32) -> Self {
            Self {
                new_root,

                new_leaf_count,
            }
        }
    }

    /// Implementation for UpdateRootInstruction
    impl UpdateRootInstruction {
        fn discriminator() -> [u8; 8] {
            [58u8, 195u8, 57u8, 246u8, 116u8, 198u8, 170u8, 138u8]
        }

        pub fn data(data: UpdateRootInstructionData) -> Self {
            Self {
                accounts: UpdateRootInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateRootInstructionAccounts) -> Self {
            self.accounts.cancel_authority =
                AccountMeta::new_readonly(accounts.cancel_authority, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.cancel_authority.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Withdraw
    // ....................................................................

    /// Main instruction struct for Withdraw
    pub struct WithdrawInstruction {
        pub accounts: WithdrawInstructionAccountMetas,
        pub data: WithdrawInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Withdraw instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawInstructionAccountMetas {
        pub beneficiary: AccountMeta,

        pub vesting_tree: AccountMeta,

        pub claim_record: AccountMeta,

        pub vault_authority: AccountMeta,

        pub vault: AccountMeta,

        pub beneficiary_ata: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Withdraw instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawInstructionAccounts {
        pub beneficiary: Pubkey,

        pub vesting_tree: Pubkey,

        pub claim_record: Pubkey,

        pub vault_authority: Pubkey,

        pub vault: Pubkey,

        pub beneficiary_ata: Pubkey,

        pub mint: Pubkey,
    }

    impl WithdrawInstructionAccounts {
        pub fn new(
            beneficiary: Pubkey,

            vesting_tree: Pubkey,

            claim_record: Pubkey,

            vault_authority: Pubkey,

            vault: Pubkey,

            beneficiary_ata: Pubkey,

            mint: Pubkey,
        ) -> Self {
            Self {
                beneficiary,

                vesting_tree,

                claim_record,

                vault_authority,

                vault,

                beneficiary_ata,

                mint,
            }
        }
    }

    /// Instruction data for Withdraw
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawInstructionData {
        pub args: WithdrawArgs,
    }

    impl WithdrawInstructionData {
        pub fn new(args: WithdrawArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for WithdrawInstruction
    impl WithdrawInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 18u8, 70u8, 156u8, 148u8, 109u8, 161u8, 34u8]
        }

        pub fn data(data: WithdrawInstructionData) -> Self {
            Self {
                accounts: WithdrawInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawInstructionAccounts) -> Self {
            self.accounts.beneficiary = AccountMeta::new(accounts.beneficiary, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self.accounts.claim_record = AccountMeta::new(accounts.claim_record, false);

            self.accounts.vault_authority =
                AccountMeta::new_readonly(accounts.vault_authority, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.beneficiary_ata = AccountMeta::new(accounts.beneficiary_ata, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.beneficiary.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.push(self.accounts.claim_record.clone());

            metas.push(self.accounts.vault_authority.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.beneficiary_ata.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawUnvested
    // ....................................................................

    /// Main instruction struct for WithdrawUnvested
    pub struct WithdrawUnvestedInstruction {
        pub accounts: WithdrawUnvestedInstructionAccountMetas,
        pub data: WithdrawUnvestedInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawUnvested instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawUnvestedInstructionAccountMetas {
        pub creator: AccountMeta,

        pub vesting_tree: AccountMeta,

        pub vault_authority: AccountMeta,

        pub vault: AccountMeta,

        pub creator_ata: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for WithdrawUnvested instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawUnvestedInstructionAccounts {
        pub creator: Pubkey,

        pub vesting_tree: Pubkey,

        pub vault_authority: Pubkey,

        pub vault: Pubkey,

        pub creator_ata: Pubkey,
    }

    impl WithdrawUnvestedInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            vesting_tree: Pubkey,

            vault_authority: Pubkey,

            vault: Pubkey,

            creator_ata: Pubkey,
        ) -> Self {
            Self {
                creator,

                vesting_tree,

                vault_authority,

                vault,

                creator_ata,
            }
        }
    }

    /// Instruction data for WithdrawUnvested
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawUnvestedInstructionData {}

    impl WithdrawUnvestedInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for WithdrawUnvestedInstruction
    impl WithdrawUnvestedInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 51u8, 30u8, 54u8, 10u8, 96u8, 116u8, 28u8]
        }

        pub fn data(data: WithdrawUnvestedInstructionData) -> Self {
            Self {
                accounts: WithdrawUnvestedInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawUnvestedInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.vesting_tree = AccountMeta::new(accounts.vesting_tree, false);

            self.accounts.vault_authority =
                AccountMeta::new_readonly(accounts.vault_authority, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.creator_ata = AccountMeta::new(accounts.creator_ata, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.vesting_tree.clone());

            metas.push(self.accounts.vault_authority.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.creator_ata.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: CampaignCancelled
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CampaignCancelled {
    pub tree: Pubkey,

    pub cancelled_at: i64,

    pub claimed_at_cancel: u64,
}

impl CampaignCancelled {
    pub fn new(tree: Pubkey, cancelled_at: i64, claimed_at_cancel: u64) -> Self {
        Self {
            tree,

            cancelled_at,

            claimed_at_cancel,
        }
    }
}

/// Custom struct: CampaignCreated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CampaignCreated {
    pub tree: Pubkey,

    pub creator: Pubkey,

    pub mint: Pubkey,

    pub total_supply: u64,

    pub leaf_count: u32,

    pub cancellable: bool,
}

impl CampaignCreated {
    pub fn new(
        tree: Pubkey,

        creator: Pubkey,

        mint: Pubkey,

        total_supply: u64,

        leaf_count: u32,

        cancellable: bool,
    ) -> Self {
        Self {
            tree,

            creator,

            mint,

            total_supply,

            leaf_count,

            cancellable,
        }
    }
}

/// Custom struct: CampaignFunded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CampaignFunded {
    pub tree: Pubkey,

    pub amount: u64,

    pub vault_balance_after: u64,
}

impl CampaignFunded {
    pub fn new(tree: Pubkey, amount: u64, vault_balance_after: u64) -> Self {
        Self {
            tree,

            amount,

            vault_balance_after,
        }
    }
}

/// Custom struct: CampaignPaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CampaignPaused {
    pub tree: Pubkey,
}

impl CampaignPaused {
    pub fn new(tree: Pubkey) -> Self {
        Self { tree }
    }
}

/// Custom struct: CampaignUnpaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CampaignUnpaused {
    pub tree: Pubkey,
}

impl CampaignUnpaused {
    pub fn new(tree: Pubkey) -> Self {
        Self { tree }
    }
}

/// Custom struct: ClaimRecord
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ClaimRecord {
    pub beneficiary: Pubkey,

    pub tree: Pubkey,

    pub claimed_amount: u64,

    pub total_entitled: u64,

    pub milestone_bitmap: [u8; 32],

    pub last_claim_at: i64,

    pub bump: u8,
}

impl ClaimRecord {
    pub fn new(
        beneficiary: Pubkey,

        tree: Pubkey,

        claimed_amount: u64,

        total_entitled: u64,

        milestone_bitmap: [u8; 32],

        last_claim_at: i64,

        bump: u8,
    ) -> Self {
        Self {
            beneficiary,

            tree,

            claimed_amount,

            total_entitled,

            milestone_bitmap,

            last_claim_at,

            bump,
        }
    }
}

/// Custom struct: ClaimRecordClosed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ClaimRecordClosed {
    pub tree: Pubkey,

    pub beneficiary: Pubkey,
}

impl ClaimRecordClosed {
    pub fn new(tree: Pubkey, beneficiary: Pubkey) -> Self {
        Self { tree, beneficiary }
    }
}

/// Custom struct: Claimed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Claimed {
    pub tree: Pubkey,

    pub beneficiary: Pubkey,

    pub leaf_index: u32,

    pub amount: u64,

    pub total_claimed_by_user: u64,

    pub total_claimed_overall: u64,

    pub milestone_idx: Option<u8>,
}

impl Claimed {
    pub fn new(
        tree: Pubkey,

        beneficiary: Pubkey,

        leaf_index: u32,

        amount: u64,

        total_claimed_by_user: u64,

        total_claimed_overall: u64,

        milestone_idx: Option<u8>,
    ) -> Self {
        Self {
            tree,

            beneficiary,

            leaf_index,

            amount,

            total_claimed_by_user,

            total_claimed_overall,

            milestone_idx,
        }
    }
}

/// Custom struct: CreateCampaignArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CreateCampaignArgs {
    pub campaign_id: u64,

    pub merkle_root: [u8; 32],

    pub leaf_count: u32,

    pub total_supply: u64,

    pub cancellable: bool,

    pub cancel_authority: Option<Pubkey>,

    pub pause_authority: Option<Pubkey>,
}

impl CreateCampaignArgs {
    pub fn new(
        campaign_id: u64,

        merkle_root: [u8; 32],

        leaf_count: u32,

        total_supply: u64,

        cancellable: bool,

        cancel_authority: Option<Pubkey>,

        pause_authority: Option<Pubkey>,
    ) -> Self {
        Self {
            campaign_id,

            merkle_root,

            leaf_count,

            total_supply,

            cancellable,

            cancel_authority,

            pause_authority,
        }
    }
}

/// Custom struct: CreateStreamArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CreateStreamArgs {
    pub campaign_id: u64,

    pub beneficiary: Pubkey,

    pub amount: u64,

    pub release_type: u8,

    pub start_time: i64,

    pub cliff_time: i64,

    pub end_time: i64,

    pub milestone_idx: u8,

    pub cancellable: bool,

    pub cancel_authority: Option<Pubkey>,

    pub pause_authority: Option<Pubkey>,
}

impl CreateStreamArgs {
    pub fn new(
        campaign_id: u64,

        beneficiary: Pubkey,

        amount: u64,

        release_type: u8,

        start_time: i64,

        cliff_time: i64,

        end_time: i64,

        milestone_idx: u8,

        cancellable: bool,

        cancel_authority: Option<Pubkey>,

        pause_authority: Option<Pubkey>,
    ) -> Self {
        Self {
            campaign_id,

            beneficiary,

            amount,

            release_type,

            start_time,

            cliff_time,

            end_time,

            milestone_idx,

            cancellable,

            cancel_authority,

            pause_authority,
        }
    }
}

/// Custom struct: RootUpdated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RootUpdated {
    pub tree: Pubkey,

    pub old_root: [u8; 32],

    pub new_root: [u8; 32],

    pub new_leaf_count: u32,
}

impl RootUpdated {
    pub fn new(tree: Pubkey, old_root: [u8; 32], new_root: [u8; 32], new_leaf_count: u32) -> Self {
        Self {
            tree,

            old_root,

            new_root,

            new_leaf_count,
        }
    }
}

/// Custom struct: UnvestedWithdrawn
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UnvestedWithdrawn {
    pub tree: Pubkey,

    pub amount: u64,
}

impl UnvestedWithdrawn {
    pub fn new(tree: Pubkey, amount: u64) -> Self {
        Self { tree, amount }
    }
}

/// Custom struct: VestingLeaf
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct VestingLeaf {
    pub leaf_index: u32,

    pub beneficiary: Pubkey,

    pub amount: u64,

    pub release_type: u8,

    pub start_time: i64,

    pub cliff_time: i64,

    pub end_time: i64,

    pub milestone_idx: u8,
}

impl VestingLeaf {
    pub fn new(
        leaf_index: u32,

        beneficiary: Pubkey,

        amount: u64,

        release_type: u8,

        start_time: i64,

        cliff_time: i64,

        end_time: i64,

        milestone_idx: u8,
    ) -> Self {
        Self {
            leaf_index,

            beneficiary,

            amount,

            release_type,

            start_time,

            cliff_time,

            end_time,

            milestone_idx,
        }
    }
}

/// Custom struct: VestingTree
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct VestingTree {
    pub creator: Pubkey,

    pub mint: Pubkey,

    pub vault: Pubkey,

    pub vault_authority: Pubkey,

    pub campaign_id: u64,

    pub merkle_root: [u8; 32],

    pub leaf_count: u32,

    pub total_supply: u64,

    pub total_claimed: u64,

    pub cancellable: bool,

    pub cancel_authority: Option<Pubkey>,

    pub cancelled_at: Option<i64>,

    pub paused: bool,

    pub pause_authority: Option<Pubkey>,

    pub created_at: i64,

    pub bump: u8,
}

impl VestingTree {
    pub fn new(
        creator: Pubkey,

        mint: Pubkey,

        vault: Pubkey,

        vault_authority: Pubkey,

        campaign_id: u64,

        merkle_root: [u8; 32],

        leaf_count: u32,

        total_supply: u64,

        total_claimed: u64,

        cancellable: bool,

        cancel_authority: Option<Pubkey>,

        cancelled_at: Option<i64>,

        paused: bool,

        pause_authority: Option<Pubkey>,

        created_at: i64,

        bump: u8,
    ) -> Self {
        Self {
            creator,

            mint,

            vault,

            vault_authority,

            campaign_id,

            merkle_root,

            leaf_count,

            total_supply,

            total_claimed,

            cancellable,

            cancel_authority,

            cancelled_at,

            paused,

            pause_authority,

            created_at,

            bump,
        }
    }
}

/// Custom struct: WithdrawArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct WithdrawArgs {
    pub release_type: u8,

    pub start_time: i64,

    pub cliff_time: i64,

    pub end_time: i64,

    pub milestone_idx: u8,
}

impl WithdrawArgs {
    pub fn new(
        release_type: u8,

        start_time: i64,

        cliff_time: i64,

        end_time: i64,

        milestone_idx: u8,
    ) -> Self {
        Self {
            release_type,

            start_time,

            cliff_time,

            end_time,

            milestone_idx,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
