name: Lint

on:
  push:
    branches: [main, dev_geral]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: >
          cargo clippy --workspace --
          -D warnings
          -A unexpected_cfgs
          -A unused_imports
          -A ambiguous_glob_reexports
          -A clippy::diverging_sub_expression
